### ISSUE TITLE
do i provide HTO couts from the filterered or raw cellranger outputs

### ISSUE THREAD

**Issue by deevdevil88** [BimberLab/cellhashR#110]
Hello,
This might be an obivous question, i guess your terminology in the description is confusing me. When you mean Raw HTO counts, do you mean non normalised HTO UMI count matrix, or do you mean the raw cellranger HTO count matrix (so all 700K CB). I assume using the filtered cellranger output makes more sense, but just confirming.

Best,
Devika

**Comment by deevdevil88** [comment]
ahh sorry it is for the GenerateCellHashCalls(), i assume i just need to provide a umi count matrix for the HTOs, but this should be limited to barcodes call as cells by cellranger already. Just confirming.

Devika

**Comment by bbimber** [comment]
Got it. The Example Usage on the README page has a code snip, albeit not that well documented. In general, use cellhashR::ProcessCountMatrix() to read and parse the UMI-collapsed data.  Something like:
```
barcodeData <- ProcessCountMatrix(rawCountData = 'myCountDir/umi_count', minCountPerCell = 5, barcodeWhitelist = c('HTO-1', 'HTO-2', 'HTO-3', 'HTO-4', 'HTO-6'))
```
The R doc is a little more informative (either do ?ProcessCountMatrix in R or see here: https://github.com/BimberLab/cellhashR/blob/f4a86dcef75f5da7a74b4e85ab42376c64499627/R/Preprocessing.R#L5. 

The rawCountData argument is the 10x h5 matrix folder. It can either be the raw or filtered count data. I believe we tend to use raw counts, but provide it with the cellbarcodeWhitelist of all cells with GEX data. This can increase the overlap in case there are GEX droplets that had weaker but usable hashing data, which might have been filtered by 10x's algorithm. I'll update the R doc to make that argument clearer.

**Comment by deevdevil88** [comment]
i see thanks that useful to know, i have usually gone with with the Cellrangers or lets say DropletUtils calling and then done demultiplexing. i wil try it with cellhashR  with the raw counts as well.

so just to confirm, `ProcessCountMatrix` still requires the HTO or FB counts either raw or filtered, not the GEX counts at all correct. only the demultiplexing with demuxEM requires the gene counts.
Best,
Devika

**Comment by bbimber** [comment]
Right, ProcessCountMatrix() needs the HTO count matrix, not GEX count-level data. The point is to provide some QC plots and do basic filtering (like dropping low count barcodes). It does take advantage of your GEX data if you provide the cellbarcodeWhitelist, which is generally the passing GEX barcodes (which might have been determined by cellranger or dropletutils).  

As you point out, demuxEM does need GEX count data, but that's the only demultiplexing algorithm that needs this.
