### ISSUE TITLE
GenerateCellHashingCells not recognising rawFeatureH5

### ISSUE THREAD

**Issue by mbassalbioinformatics** [BimberLab/cellhashR#116]
Hi again
So in trying to run GenerateCellHashingCells, im passing through the h5 file path but keep getting the error

```
Error in GenerateCellHashingCalls(barcodeMatrix = barcodeData, methods = c("htodemux",  : 
  demuxmix requires the path to the 10x gene expression raw_feature_bc_matrix.h5 file. Please provide this as the argument demuxmix.rawFeatureMatrixH5 = <filepath>
```

Ive passed in the full path both directly or saved as a variable but still keep getting the same problem. Thoughts?

**Comment by mbassalbioinformatics** [comment]
Ok so the issue is that on teh main github page you have written
```
df <- GenerateCellHashingCalls(barcodeMatrix = barcodeMatrix, methods = c('bff_cluster', 'demuxem'), demuxem.rawFeatureMatrixH5 = h5File)
```

but the code is now looking for
```
...demuxmix.rawFeatureMatrixH5=...)
```

demuxem (page) VS demuxmix (code)

Looks like the code was changed but the doc page wasn't. Wil leave the issue open till you look at it and can fix up the documentation where required.
Thanks

**Comment by bbimber** [comment]
@mbassalbioinformatics, yes, that is true. the latest version simplifies supplying the h5file argument for demuxem/demuxmix. Please see here: https://github.com/BimberLab/cellhashR#providing-h5-file-to-demuxemdemuxmix. Feel free to re-open if you have issues with this.
