### ISSUE TITLE
No HTO/GEX overlap in demuxmix

### ISSUE THREAD

**Issue by wlason** [BimberLab/cellhashR#126]
Hi! Thanks so much for the awesome package :)
I am running cellhashR with `methods = c("htodemux", "multiseq", "dropletutils", "demuxem", "demuxmix", "bff_raw", "bff_cluster")`. All the methods produce output except for demuxmix. The error I am getting is:

`[1] "Starting demuxmix"`
`[1] "Removing cell barcode suffixes from input GEX matrix"`
`[1] "Error generating demuxmix calls, aborting"`
`[1] "The cellbarcodes in the HTO and GEX matricies do not overlap. Please check inputs files"`
`No traceback available `
`[1] "Generating consensus calls"`
`[1] "No algorithms produced calls, aborting"`

Can you help? Is there a way for me to manually check the overlap between the .h5 file and the HTO matrix?

I noted that I get `Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')` for other methods, might my issue be related to that?

**Comment by bbimber** [comment]
@wlason, can you please do these:

1) change methods to pick just one caller and dont use demuxmix. I want to see whether this is a general issue or something specific to that.

2) Given that error, I think it's more likely you have a general issue, and demuxmix happened to be the algorithm to run first. Can you please post the entire command you ran?

**Comment by bbimber** [comment]
OK, that helps. Can you try:
```
gexCounts <- DropletUtils::read10xCounts(h5)
head(rownames(gexCounts ))

head(colnames(matrix))

```

**Comment by bbimber** [comment]
Also, you can see how it loads the input files and inspects barcodes here: https://github.com/BimberLab/cellhashR/blob/918ede986793ea7ddb7c5edb5167f317c1abb387/R/demuxmix.R#L20.

**Comment by wlason** [comment]
The overlap seems to be good:
`> head(gexCounts$Barcode)`
`[1] "AAACCTGAGAAACCAT-1" "AAACCTGAGAAACCGC-1" "AAACCTGAGAAACCTA-1"
[4] "AAACCTGAGAAACGAG-1" "AAACCTGAGAAACGCC-1" "AAACCTGAGAAAGTGG-1"`

`> head(colnames(matrix))`
`[1] "AAACCTGAGCGTGTCC-1" "AAACCTGAGTGTTTGC-1" "AAACCTGCATTGCGGC-1"
[4] "AAACCTGGTAAATGAC-1" "AAACCTGGTCATGCAT-1" "AAACCTGGTCTGCAAT-1"`

`> length(intersect(gexCounts$Barcode, colnames(matrix)))`
`[1] 5298`

5298 is the number of cells DropletUtils called above. I also tried to swap `Seurat::Read10X(data)` for `DropletUtils::read10xCounts(data)`, but it didn't help.

**Comment by wlason** [comment]
I think this line is causing a problem, making cellhashR strip the barcode suffixes, even though it's not needed:
https://github.com/BimberLab/cellhashR/blob/918ede986793ea7ddb7c5edb5167f317c1abb387/R/demuxmix.R#L25
It has 'colnames' twice.

**Comment by bbimber** [comment]
Indeed, that's right.  I was about to comment, but I think this explains why we never see the issue:

- Our code tends to strip the "-1" suffixes. You input didn't
- This duplicate colnames() is a bug. In our case, it means the code would always try to strip the suffix.
- That is fine for us, since we're expecting those to be removed. You are not.

Anyway, I'll patch that shortly. In the interim, you can strip the '-1' from the count matrix and this would run.

Once this passes tests I'll merge is: https://github.com/BimberLab/cellhashR/pull/127

Thanks for pointing this out.
