### ISSUE TITLE
Cran availability

### ISSUE THREAD

**Issue by mari-ga** [BimberLab/cellhashR#139]
Hi, 

First of all, thank you very much for this tool!

I've been working with this tool across various environments, and I'd like to know if you've considered making it available on CRAN or Bioconductor. Doing so would greatly simplify the installation process and enhance accessibility for a wider audience. 

Thank you very much for your consideration.

**Comment by bbimber** [comment]
Thanks for your interest. There are really two obstacles that prevented us from looking into CRAN. First, cellhashR historically depending on a number of packages that only had installation available either through github_install() or BioConductor. This also depends on a number of python packages. As I look at this today, preprocessCore still needs a github-based installation, which last time I checked was a problem for CRAN. I see your point and will give this another look; however, it really depends on how difficult publishing on either CRAN or BioConductor would be with those dependencies.

**Comment by mari-ga** [comment]
Thank you very much for your quick answer!
I was checking that preprocess Core is already available in BioConductor, perhaps that could be useful. However, I understand that some Python packages are difficult.
Again thank you very much, I hope that making the package available is possible in the future. Whether through CRAN or Bioconductor, it would be truly fantastic!
