### ISSUE TITLE
If path finish with "/", ProcessCountMatrix doesn't work

### ISSUE THREAD

**Issue by domi84** [BimberLab/cellhashR#67]
Hi there,
thanks for developing cellhashR, seems very interesting. 
I used CITEseq-count to generate the umi_count folder, but I realized when you put a "/" in the end of the path, ProcessCountMatrix doesn't work:

```
barcodeData <- ProcessCountMatrix(rawCountData = "C:/FILES/10X/10X first complete run/2189_NS215_0118_Mariola_20210804/HTO_map/DS-1/umi_count/", minCountPerCell = 5)
```

Error:
```
Error in .LoadCountMatrix(rawCountData = rawCountData, barcodeBlacklist = barcodeBlacklist,  : 
  File does not exist: C:/FILES/10X/10X first complete run/2189_NS215_0118_Mariola_20210804/HTO_map/DS-1/umi_count/
```

But if you remove the "/" it works
```
barcodeData <- ProcessCountMatrix(rawCountData = "C:/FILES/10X/10X first complete run/2189_NS215_0118_Mariola_20210804/HTO_map/DS-1/umi_count", minCountPerCell = 5)
```

Other tools such as Seurat recognize the path with or without the final "/", I thought would be helpful to have that.
Thanks

**Comment by bbimber** [comment]
@domi84 The latest version of the package has a fix for this - thanks again for reporting it!
